name: TestPlugin
version: 1.0
author: EliteJan96
main: de.EliteJan96.Main.Main
commands:
  heile:
    description: Heilt (andere) Spieler.
    usage: /<command> [Spieler]
  tp:
    description: Teleportiert dich.
    usage: /<command> <Spieler>
  team:
    description: Teamcommand
    usage: /<command>
  vanish:
    description: Macht dich (un)sichtbar
    usage: /<command>
    aliases: [v, unsichtbar, sichtbar]
  msg:
    description: MSG-Command
    usage: /<command <Spieler> <Nachricht>
    aliases: [tell, t, send, schreibe, nachricht]
  r:
    description: R-Command
    usage: /<command> <Nachricht>
    aliases: [reply, antwort, antworten, re]